# Generated by Django 3.2.5 on 2023-03-01 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='advance_best_time',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='user',
            name='advance_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='beginner_best_time',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='user',
            name='beginner_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='current_streak',
            field=models.IntegerField(default=0),
        ),
    ]
