# Generated by Django 4.1.7 on 2023-03-02 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20230301_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='advance_best_time',
        ),
        migrations.RemoveField(
            model_name='user',
            name='advance_count',
        ),
        migrations.RemoveField(
            model_name='user',
            name='beginner_best_time',
        ),
        migrations.RemoveField(
            model_name='user',
            name='beginner_count',
        ),
        migrations.RemoveField(
            model_name='user',
            name='current_streak',
        ),
    ]
