# Generated by Django 4.1.7 on 2023-03-02 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WordStoreAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=30)),
                ('definition', models.TextField(max_length=250)),
                ('audio_file', models.FileField(upload_to='kalamkaari/audio/advance')),
            ],
        ),
        migrations.CreateModel(
            name='WordStoreBeginner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=30)),
                ('definition', models.TextField(max_length=250)),
                ('audio_file', models.FileField(upload_to='kalamkaari/audio/beginner')),
            ],
        ),
        migrations.CreateModel(
            name='kalamkaariProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beginner_count', models.IntegerField(default=0)),
                ('advance_count', models.IntegerField(default=0)),
                ('beginner_best_time', models.IntegerField(default=1000)),
                ('advance_best_time', models.IntegerField(default=1000)),
                ('current_streak', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
