# Generated by Django 4.1.7 on 2023-02-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='words_store_advance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=30)),
                ('defination', models.TextField(max_length=250)),
                ('audio_file', models.FileField(upload_to='kalamkaari/audio/advance')),
            ],
        ),
        migrations.CreateModel(
            name='words_store_beginner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=30)),
                ('defination', models.TextField(max_length=250)),
                ('audio_file', models.FileField(upload_to='kalamkaari/audio/beginner')),
            ],
        ),
    ]
