# Generated by Django 3.2.5 on 2023-03-01 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kalamkaari', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='words_store_advance',
            new_name='WordStoreAdvance',
        ),
        migrations.RenameModel(
            old_name='words_store_beginner',
            new_name='WordStoreBeginner',
        ),
        migrations.RenameField(
            model_name='wordstoreadvance',
            old_name='defination',
            new_name='definition',
        ),
        migrations.RenameField(
            model_name='wordstorebeginner',
            old_name='defination',
            new_name='definition',
        ),
    ]
