# Generated by Django 4.1.7 on 2023-03-01 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kalamkaari', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='words_store_advance',
            new_name='WordStoreAdvance',
        ),
        migrations.RenameModel(
            old_name='words_store_beginner',
            new_name='WordStoreBeginner',
        ),
        migrations.RenameField(
            model_name='wordstoreadvance',
            old_name='defination',
            new_name='definition',
        ),
        migrations.RenameField(
            model_name='wordstorebeginner',
            old_name='defination',
            new_name='definition',
        ),
        migrations.CreateModel(
            name='kalamkaariProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beginner_count', models.IntegerField(default=0)),
                ('advance_count', models.IntegerField(default=0)),
                ('beginner_best_time', models.IntegerField(default=1000)),
                ('advance_best_time', models.IntegerField(default=1000)),
                ('current_streak', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
