# Generated by Django 4.1.7 on 2023-03-06 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalamkaari', '0002_alter_wordstoreadvance_audio_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordstoreadvance',
            name='audio_file',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='wordstorebeginner',
            name='audio_file',
            field=models.FileField(upload_to=''),
        ),
    ]
